from pathlib import Path


APP_ROOT = Path(__file__).resolve().parent.parent
RECORDINGS_ROOT = APP_ROOT / "recordings"
APP_SETTINGS_FILE = APP_ROOT / "app_settings.json"

MIC_FILE_NAME = "mic.ogg"
DESKTOP_FILE_NAME = "desktop.ogg"
MIX_FILE_NAME = "mix.ogg"
TRANSCRIPT_FILE_NAME = "transcript.txt"
METADATA_FILE_NAME = "meta.json"

SAMPLE_RATE = 48_000
BLOCK_FRAMES = 4_800
MIN_SPEAKER_GAP = 6.0
MAX_MERGED_SEGMENT_DURATION = 120.0
MAX_MERGED_SEGMENT_WORDS = 220
MAX_OVERLAP_FOR_MERGE = 2.5
WORD_PAUSE_SPLIT_GAP = 1.35
SHORT_SEGMENT_WORDS = 4
SHORT_SEGMENT_BRIDGE_GAP = 12.0
VAD_MIN_SILENCE_DURATION_MS = 450
VAD_SPEECH_PAD_MS = 120
MIN_AUDIO_RMS = 0.0025
NO_SPEECH_PROB_THRESHOLD = 0.60

DEFAULT_SELF_LABEL = "Я"
DEFAULT_OTHER_LABEL = "Собеседник"
